# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f45a7b0a77b2c2e640973462447181cf719019d9c15b01e9056a397981355529885fd9364921b6b4b1133d7ee437665361286f1b4892adca2be4dc81c25035be

test:
  secret_key_base: a539a0f725f66f9d6d6faefa77dc79c638acc77c4b778bb7a50dfc19e9f868a8147a6a9ba7a0d1ef279684bebf1733eb102e2eb25b4f5fc3537e76b3229d8123

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
